version: 3.0.0

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M # limit to 200MB of memory

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 250M # limit to 250MB of memory

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    network_mode: host
    restart: unless-stopped
